# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(885, 358)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_notify = QtGui.QLabel(self.centralwidget)
        self.label_notify.setGeometry(QtCore.QRect(90, 10, 701, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_notify.setFont(font)
        self.label_notify.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notify.setObjectName(_fromUtf8("label_notify"))
        self.label_port_text = QtGui.QLabel(self.centralwidget)
        self.label_port_text.setGeometry(QtCore.QRect(40, 70, 59, 16))
        self.label_port_text.setObjectName(_fromUtf8("label_port_text"))
        self.label_port_val = QtGui.QLabel(self.centralwidget)
        self.label_port_val.setGeometry(QtCore.QRect(110, 70, 171, 16))
        self.label_port_val.setObjectName(_fromUtf8("label_port_val"))
        self.label_firmware_version_text = QtGui.QLabel(self.centralwidget)
        self.label_firmware_version_text.setGeometry(QtCore.QRect(350, 70, 121, 16))
        self.label_firmware_version_text.setObjectName(_fromUtf8("label_firmware_version_text"))
        self.label_firmware_version_val = QtGui.QLabel(self.centralwidget)
        self.label_firmware_version_val.setGeometry(QtCore.QRect(500, 70, 59, 16))
        self.label_firmware_version_val.setObjectName(_fromUtf8("label_firmware_version_val"))
        self.label_uarm_sn_text = QtGui.QLabel(self.centralwidget)
        self.label_uarm_sn_text.setGeometry(QtCore.QRect(620, 70, 71, 16))
        self.label_uarm_sn_text.setObjectName(_fromUtf8("label_uarm_sn_text"))
        self.label_uarm_sn_val = QtGui.QLabel(self.centralwidget)
        self.label_uarm_sn_val.setGeometry(QtCore.QRect(708, 70, 131, 20))
        self.label_uarm_sn_val.setObjectName(_fromUtf8("label_uarm_sn_val"))
        self.label_manual_calibration = QtGui.QLabel(self.centralwidget)
        self.label_manual_calibration.setGeometry(QtCore.QRect(340, 110, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_manual_calibration.setFont(font)
        self.label_manual_calibration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_manual_calibration.setObjectName(_fromUtf8("label_manual_calibration"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(630, 160, 171, 131))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_linear_servo_17 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_linear_servo_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_17.setObjectName(_fromUtf8("label_linear_servo_17"))
        self.horizontalLayout_23.addWidget(self.label_linear_servo_17)
        self.label_stretch_left_value = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_stretch_left_value.setObjectName(_fromUtf8("label_stretch_left_value"))
        self.horizontalLayout_23.addWidget(self.label_stretch_left_value)
        self.f_stretch_left_flag = QtGui.QFrame(self.verticalLayoutWidget_6)
        self.f_stretch_left_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_stretch_left_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_stretch_left_flag.setObjectName(_fromUtf8("f_stretch_left_flag"))
        self.horizontalLayout_23.addWidget(self.f_stretch_left_flag)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_linear_servo_18 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_linear_servo_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_18.setObjectName(_fromUtf8("label_linear_servo_18"))
        self.horizontalLayout_24.addWidget(self.label_linear_servo_18)
        self.label_stretch_right_value = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_stretch_right_value.setObjectName(_fromUtf8("label_stretch_right_value"))
        self.horizontalLayout_24.addWidget(self.label_stretch_right_value)
        self.f_stretch_right_flag = QtGui.QFrame(self.verticalLayoutWidget_6)
        self.f_stretch_right_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_stretch_right_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_stretch_right_flag.setObjectName(_fromUtf8("f_stretch_right_flag"))
        self.horizontalLayout_24.addWidget(self.f_stretch_right_flag)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.button_manual_calibration_confirm = QtGui.QPushButton(self.centralwidget)
        self.button_manual_calibration_confirm.setGeometry(QtCore.QRect(790, 20, 91, 32))
        self.button_manual_calibration_confirm.setObjectName(_fromUtf8("button_manual_calibration_confirm"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 160, 251, 131))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_linear_servo_10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_10.setObjectName(_fromUtf8("label_linear_servo_10"))
        self.horizontalLayout_16.addWidget(self.label_linear_servo_10)
        self.label_linear_servo1_intercept = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo1_intercept.setObjectName(_fromUtf8("label_linear_servo1_intercept"))
        self.horizontalLayout_16.addWidget(self.label_linear_servo1_intercept)
        self.label_linear_servo1_slope = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo1_slope.setObjectName(_fromUtf8("label_linear_servo1_slope"))
        self.horizontalLayout_16.addWidget(self.label_linear_servo1_slope)
        self.f_linear_servo1_flag = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.f_linear_servo1_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_linear_servo1_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_linear_servo1_flag.setObjectName(_fromUtf8("f_linear_servo1_flag"))
        self.horizontalLayout_16.addWidget(self.f_linear_servo1_flag)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_linear_servo_11 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_11.setObjectName(_fromUtf8("label_linear_servo_11"))
        self.horizontalLayout_17.addWidget(self.label_linear_servo_11)
        self.label_linear_servo2_intercept = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo2_intercept.setObjectName(_fromUtf8("label_linear_servo2_intercept"))
        self.horizontalLayout_17.addWidget(self.label_linear_servo2_intercept)
        self.label_linear_servo2_slope = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo2_slope.setObjectName(_fromUtf8("label_linear_servo2_slope"))
        self.horizontalLayout_17.addWidget(self.label_linear_servo2_slope)
        self.f_linear_servo2_flag = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.f_linear_servo2_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_linear_servo2_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_linear_servo2_flag.setObjectName(_fromUtf8("f_linear_servo2_flag"))
        self.horizontalLayout_17.addWidget(self.f_linear_servo2_flag)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_linear_servo_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_12.setObjectName(_fromUtf8("label_linear_servo_12"))
        self.horizontalLayout_18.addWidget(self.label_linear_servo_12)
        self.label_linear_servo3_intercept = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo3_intercept.setObjectName(_fromUtf8("label_linear_servo3_intercept"))
        self.horizontalLayout_18.addWidget(self.label_linear_servo3_intercept)
        self.label_linear_servo3_slope = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo3_slope.setObjectName(_fromUtf8("label_linear_servo3_slope"))
        self.horizontalLayout_18.addWidget(self.label_linear_servo3_slope)
        self.f_linear_servo3_flag = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.f_linear_servo3_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_linear_servo3_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_linear_servo3_flag.setObjectName(_fromUtf8("f_linear_servo3_flag"))
        self.horizontalLayout_18.addWidget(self.f_linear_servo3_flag)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_linear_servo_13 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_13.setObjectName(_fromUtf8("label_linear_servo_13"))
        self.horizontalLayout_19.addWidget(self.label_linear_servo_13)
        self.label_linear_servo4_intercept = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo4_intercept.setObjectName(_fromUtf8("label_linear_servo4_intercept"))
        self.horizontalLayout_19.addWidget(self.label_linear_servo4_intercept)
        self.label_linear_servo4_slope = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_linear_servo4_slope.setObjectName(_fromUtf8("label_linear_servo4_slope"))
        self.horizontalLayout_19.addWidget(self.label_linear_servo4_slope)
        self.f_linear_servo4_flag = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.f_linear_servo4_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_linear_servo4_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_linear_servo4_flag.setObjectName(_fromUtf8("f_linear_servo4_flag"))
        self.horizontalLayout_19.addWidget(self.f_linear_servo4_flag)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(350, 160, 201, 131))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_linear_servo_14 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_linear_servo_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_14.setObjectName(_fromUtf8("label_linear_servo_14"))
        self.horizontalLayout_20.addWidget(self.label_linear_servo_14)
        self.label_manual_servo1_value = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_manual_servo1_value.setObjectName(_fromUtf8("label_manual_servo1_value"))
        self.horizontalLayout_20.addWidget(self.label_manual_servo1_value)
        self.f_manual_servo1_flag = QtGui.QFrame(self.verticalLayoutWidget_4)
        self.f_manual_servo1_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_manual_servo1_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_manual_servo1_flag.setObjectName(_fromUtf8("f_manual_servo1_flag"))
        self.horizontalLayout_20.addWidget(self.f_manual_servo1_flag)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_linear_servo_15 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_linear_servo_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_15.setObjectName(_fromUtf8("label_linear_servo_15"))
        self.horizontalLayout_21.addWidget(self.label_linear_servo_15)
        self.label_manual_servo2_value = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_manual_servo2_value.setObjectName(_fromUtf8("label_manual_servo2_value"))
        self.horizontalLayout_21.addWidget(self.label_manual_servo2_value)
        self.f_manual_servo2_flag = QtGui.QFrame(self.verticalLayoutWidget_4)
        self.f_manual_servo2_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_manual_servo2_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_manual_servo2_flag.setObjectName(_fromUtf8("f_manual_servo2_flag"))
        self.horizontalLayout_21.addWidget(self.f_manual_servo2_flag)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_linear_servo_16 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_linear_servo_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_servo_16.setObjectName(_fromUtf8("label_linear_servo_16"))
        self.horizontalLayout_22.addWidget(self.label_linear_servo_16)
        self.label_manual_servo3_value = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_manual_servo3_value.setObjectName(_fromUtf8("label_manual_servo3_value"))
        self.horizontalLayout_22.addWidget(self.label_manual_servo3_value)
        self.f_manual_servo3_flag = QtGui.QFrame(self.verticalLayoutWidget_4)
        self.f_manual_servo3_flag.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_manual_servo3_flag.setFrameShadow(QtGui.QFrame.Raised)
        self.f_manual_servo3_flag.setObjectName(_fromUtf8("f_manual_servo3_flag"))
        self.horizontalLayout_22.addWidget(self.f_manual_servo3_flag)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.label_stretch_calirbation = QtGui.QLabel(self.centralwidget)
        self.label_stretch_calirbation.setGeometry(QtCore.QRect(620, 110, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_stretch_calirbation.setFont(font)
        self.label_stretch_calirbation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stretch_calirbation.setObjectName(_fromUtf8("label_stretch_calirbation"))
        self.label_linear_title = QtGui.QLabel(self.centralwidget)
        self.label_linear_title.setGeometry(QtCore.QRect(40, 110, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_linear_title.setFont(font)
        self.label_linear_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear_title.setObjectName(_fromUtf8("label_linear_title"))
        self.button_calibration_start = QtGui.QPushButton(self.centralwidget)
        self.button_calibration_start.setGeometry(QtCore.QRect(10, 20, 71, 32))
        self.button_calibration_start.setObjectName(_fromUtf8("button_calibration_start"))
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.action_start = QtGui.QAction(mainWindow)
        self.action_start.setObjectName(_fromUtf8("action_start"))
        self.action_check_update = QtGui.QAction(mainWindow)
        self.action_check_update.setObjectName(_fromUtf8("action_check_update"))
        self.action_quit = QtGui.QAction(mainWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_fresh = QtGui.QAction(mainWindow)
        self.action_fresh.setObjectName(_fromUtf8("action_fresh"))
        self.menuFile.addAction(self.action_start)
        self.menuFile.addAction(self.action_fresh)
        self.menuFile.addAction(self.action_check_update)
        self.menuFile.addAction(self.action_quit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "uArm Calibration Tool", None))
        self.label_notify.setText(_translate("mainWindow", "Wating For Connect", None))
        self.label_port_text.setText(_translate("mainWindow", "Port:", None))
        self.label_port_val.setText(_translate("mainWindow", "N/A", None))
        self.label_firmware_version_text.setText(_translate("mainWindow", "Firmware Version:", None))
        self.label_firmware_version_val.setText(_translate("mainWindow", "N/A", None))
        self.label_uarm_sn_text.setText(_translate("mainWindow", "uArm SN:", None))
        self.label_uarm_sn_val.setText(_translate("mainWindow", "N/A", None))
        self.label_manual_calibration.setText(_translate("mainWindow", "2. Manual Calibration", None))
        self.label_linear_servo_17.setText(_translate("mainWindow", "Left", None))
        self.label_stretch_left_value.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo_18.setText(_translate("mainWindow", "Right", None))
        self.label_stretch_right_value.setText(_translate("mainWindow", "N/A", None))
        self.button_manual_calibration_confirm.setText(_translate("mainWindow", "Confirm", None))
        self.label_linear_servo_10.setText(_translate("mainWindow", "1", None))
        self.label_linear_servo1_intercept.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo1_slope.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo_11.setText(_translate("mainWindow", "2", None))
        self.label_linear_servo2_intercept.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo2_slope.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo_12.setText(_translate("mainWindow", "3", None))
        self.label_linear_servo3_intercept.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo3_slope.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo_13.setText(_translate("mainWindow", "4", None))
        self.label_linear_servo4_intercept.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo4_slope.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo_14.setText(_translate("mainWindow", "1", None))
        self.label_manual_servo1_value.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo_15.setText(_translate("mainWindow", "2", None))
        self.label_manual_servo2_value.setText(_translate("mainWindow", "N/A", None))
        self.label_linear_servo_16.setText(_translate("mainWindow", "3", None))
        self.label_manual_servo3_value.setText(_translate("mainWindow", "N/A", None))
        self.label_stretch_calirbation.setText(_translate("mainWindow", "3. Stretch Calirbation", None))
        self.label_linear_title.setText(_translate("mainWindow", "1. Linear Calibration", None))
        self.button_calibration_start.setText(_translate("mainWindow", "Start", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.action_start.setText(_translate("mainWindow", "Start", None))
        self.action_start.setShortcut(_translate("mainWindow", "F4", None))
        self.action_check_update.setText(_translate("mainWindow", "Check Update", None))
        self.action_check_update.setShortcut(_translate("mainWindow", "F9", None))
        self.action_quit.setText(_translate("mainWindow", "Quit", None))
        self.action_fresh.setText(_translate("mainWindow", "Refresh", None))
        self.action_fresh.setShortcut(_translate("mainWindow", "F5", None))

